In [1]:
import ccxt
import time
import pandas as pd
from datetime import datetime

In [7]:
start_date = '2018-01-01T00:00:00Z'
end_date = '2019-12-31T00:00:00Z'
symbols = ['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'NEO/USDT']
timeframe = '1d'

In [48]:
exchange = ccxt.binance()

In [ ]:
columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume']

In [15]:
start_ts = exchange.parse8601(start_date)
end_ts = exchange.parse8601(end_date)

In [49]:
all_data = exchange.fetch_ohlcv('BTC/USDT', timeframe, since=start_ts, limit=1000)

In [51]:
time_close_dict = {c[0]: c[4] for c in all_data if c[0] <= end_ts}

In [56]:
all_data

[[1514764800000, 74.854, 80.0, 71.05, 78.299, 81411.846],
 [1514851200000, 78.255, 96.997, 78.246, 89.696, 200642.887],
 [1514937600000, 89.6, 104.885, 85.3, 103.505, 157777.608],
 [1515024000000, 103.506, 108.88, 94.5, 97.669, 112336.601],
 [1515110400000, 97.669, 106.997, 88.0, 95.134, 136754.802],
 [1515196800000, 95.135, 102.869, 90.392, 100.491, 67541.119],
 [1515283200000, 100.092, 109.0, 97.0, 103.096, 51435.255],
 [1515369600000, 102.599, 108.899, 82.5, 101.361, 96541.847],
 [1515456000000, 101.262, 131.0, 100.879, 126.7, 163943.227],
 [1515542400000, 126.911, 127.886, 106.331, 122.239, 217513.907],
 [1515628800000, 122.871, 125.0, 91.1, 107.701, 172426.94],
 [1515715200000, 107.701, 126.099, 101.49, 123.111, 84911.316],
 [1515801600000, 123.111, 149.98, 119.0, 139.777, 114714.28],
 [1515888000000, 139.012, 186.0, 132.0, 170.0, 241962.311],
 [1515974400000, 170.0, 198.6, 143.39, 189.382, 404036.922],
 [1516060800000, 189.382, 190.7, 88.888, 137.502, 1191407.185],
 [1516147200000, 137.502, 156.19, 91.34, 142.0, 1578232.549],
 [1516233600000, 142.0, 159.223, 127.0, 139.501, 780008.366],
 [1516320000000, 138.657, 148.25, 126.31, 139.523, 420299.152],
 [1516406400000, 139.523, 157.26, 137.579, 149.999, 319117.756],
 [1516492800000, 150.287, 151.0, 124.0, 132.589, 301735.925],
 [1516579200000, 132.899, 139.0, 110.85, 123.314, 315449.808],
 [1516665600000, 123.347, 131.0, 108.5, 122.77, 288073.929],
 [1516752000000, 122.77, 147.0, 116.8, 138.0, 365376.365],
 [1516838400000, 138.0, 148.329, 135.07, 138.024, 218161.791],
 [1516924800000, 138.023, 141.5, 123.79, 137.621, 252032.465],
 [1517011200000, 137.7, 143.0, 134.268, 141.959, 110428.369],
 [1517097600000, 141.959, 156.0, 141.0, 154.101, 165493.158],
 [1517184000000, 154.1, 169.2, 148.7, 168.289, 283531.324],
 [1517270400000, 168.287, 169.999, 136.45, 146.185, 440562.694],
 [1517356800000, 146.185, 147.9, 132.901, 146.488, 243709.537],
 [1517443200000, 146.101, 147.6, 112.78, 126.5, 397262.992],
 [1517529600000, 126.5, 132.03, 93.94, 121.155, 763993.41],
 [1517616000000, 121.155, 129.93, 108.05, 124.601, 346512.532],
 [1517702400000, 124.601, 125.0, 100.64, 107.025, 355973.816],
 [1517788800000, 107.025, 109.85, 73.626, 82.136, 969744.83],
 [1517875200000, 82.137, 110.21, 64.3, 103.534, 1649845.116],
 [1517961600000, 103.535, 119.5, 93.0, 102.337, 1153333.09],
 [1518048000000, 102.003, 111.0, 101.302, 109.2, 36451.642],
 [1518134400000, 109.32, 116.0, 109.32, 114.52, 310399.422],
 [1518220800000, 114.572, 119.79, 100.301, 107.3, 484147.251],
 [1518307200000, 107.3, 111.84, 93.1, 101.707, 558336.262],
 [1518393600000, 101.661, 115.12, 101.661, 111.89, 491482.53],
 [1518480000000, 111.897, 113.0, 106.222, 108.5, 249026.013],
 [1518566400000, 108.384, 123.0, 108.23, 122.001, 363358.118],
 [1518652800000, 121.923, 124.5, 116.1, 121.003, 361031.833],
 [1518739200000, 121.003, 129.45, 117.601, 127.415, 267448.945],
 [1518825600000, 127.415, 138.76, 127.03, 134.999, 297993.945],
 [1518912000000, 134.999, 136.878, 120.748, 125.121, 299278.192],
 [1518998400000, 125.138, 137.56, 123.702, 136.391, 235288.119],
 [1519084800000, 136.391, 140.849, 123.8, 124.66, 300979.475],
 [1519171200000, 124.661, 128.551, 114.321, 117.697, 416877.348],
 [1519257600000, 117.69, 125.85, 109.001, 111.478, 415629.997],
 [1519344000000, 111.478, 122.6, 108.12, 118.336, 368180.6],
 [1519430400000, 118.519, 123.999, 110.521, 115.25, 282959.435],
 [1519516800000, 115.2, 118.0, 112.11, 116.789, 161241.435],
 [1519603200000, 116.8, 136.9, 115.4, 134.402, 467939.087],
 [1519689600000, 134.4, 145.0, 130.1, 139.856, 509343.173],
 [1519776000000, 140.29, 143.995, 129.5, 131.7, 366472.698],
 [1519862400000, 131.623, 135.499, 124.8, 128.555, 358987.805],
 [1519948800000, 128.593, 130.2, 121.597, 123.58, 171374.122],
 [1520035200000, 123.57, 128.5, 120.6, 121.379, 168554.349],
 [1520121600000, 121.38, 125.0, 115.3, 119.3, 227594.282],
 [1520208000000, 119.322, 119.85, 111.013, 111.183, 223296.022],
 [1520294400000, 111.17, 114.848, 101.65, 104.357, 404722.002],
 [1520380800000, 104.409, 114.0, 86.59, 100.1, 779626.205],
 [1520467200000, 100.07, 102.116, 89.01, 90.402, 442049.61],
 [1520553600000, 90.52, 93.6, 79.4, 91.64, 703642.561],
 [1520640000000, 91.64, 93.8, 84.07, 84.73, 373435.948],
 [1520726400000, 84.61, 92.0, 81.111, 90.445, 333691.122],
 [1520812800000, 90.445, 92.7, 83.0, 85.25, 290121.508],
 [1520899200000, 85.25, 88.25, 80.9, 83.0, 313261.867],
 [1520985600000, 82.985, 84.7, 68.0, 71.2, 447131.548],
 [1521072000000, 71.2, 72.85, 64.664, 69.06, 647759.517],
 [1521158400000, 69.0, 71.7, 65.5, 67.288, 400000.686],
 [1521244800000, 67.288, 68.94, 60.02, 60.2, 346708.71],
 [1521331200000, 60.2, 68.32, 48.78, 65.2, 1390876.96],
 [1521417600000, 65.2, 73.394, 62.226, 72.53, 1141470.907],
 [1521504000000, 72.485, 79.8, 66.4, 75.713, 932106.963],
 [1521590400000, 75.713, 77.9, 70.5, 72.58, 742100.257],
 [1521676800000, 72.517, 75.019, 66.001, 69.289, 665550.831],
 [1521763200000, 69.209, 69.411, 63.35, 68.847, 577187.138],
 [1521849600000, 68.867, 70.2, 65.01, 65.225, 389734.483],
 [1521936000000, 65.225, 67.497, 63.38, 65.521, 287118.892],
 [1522022400000, 65.645, 66.2, 55.132, 58.879, 641822.044],
 [1522108800000, 58.879, 60.55, 51.867, 55.365, 688834.662],
 [1522195200000, 55.365, 60.01, 54.865, 57.165, 320351.498],
 [1522281600000, 57.106, 57.34, 51.08, 51.606, 658039.602],
 [1522368000000, 51.678, 53.998, 48.8, 50.296, 787045.059],
 [1522454400000, 50.27, 52.988, 49.6, 49.918, 387569.925],
 [1522540800000, 49.918, 50.549, 44.691, 47.25, 418495.075],
 [1522627200000, 47.324, 50.5, 46.5, 48.816, 321028.941],
 [1522713600000, 48.798, 53.999, 48.4, 53.273, 428284.629],
 [1522800000000, 53.273, 53.449, 46.326, 47.537, 425901.102],
 [1522886400000, 47.537, 48.32, 45.5, 46.954, 298190.857],
 [1522972800000, 46.982, 47.479, 44.1, 44.748, 189649.155],
 [1523059200000, 44.748, 47.981, 44.62, 46.592, 219646.632],
 [1523145600000, 46.592, 49.4, 46.379, 49.37, 162289.595],
 [1523232000000, 49.319, 57.375, 48.9, 53.02, 1025335.889],
 [1523318400000, 53.041, 53.286, 49.199, 52.734, 364257.094],
 [1523404800000, 52.694, 59.6, 52.337, 58.293, 578614.292],
 [1523491200000, 58.315, 67.408, 54.32, 67.15, 1071889.268],
 [1523577600000, 67.089, 68.59, 61.25, 62.269, 750766.696],
 [1523664000000, 62.431, 65.87, 61.5, 64.179, 393477.038],
 [1523750400000, 64.125, 70.875, 64.0, 70.617, 424476.096],
 [1523836800000, 70.536, 71.5, 64.0, 66.801, 512701.791],
 [1523923200000, 66.897, 70.3, 65.25, 65.66, 330085.745],
 [1524009600000, 65.63, 73.8, 65.531, 72.91, 341104.914],
 [1524096000000, 72.909, 75.125, 70.5, 73.949, 356586.225],
 [1524182400000, 73.952, 79.758, 71.802, 79.14, 486616.213],
 [1524268800000, 79.13, 79.75, 70.26, 74.748, 568751.252],
 [1524355200000, 74.748, 77.41, 72.699, 73.615, 295209.364],
 [1524441600000, 73.615, 78.039, 73.321, 76.2, 242499.073],
 [1524528000000, 76.122, 84.628, 76.107, 82.412, 504812.04],
 [1524614400000, 82.412, 82.915, 68.211, 71.549, 845252.143],
 [1524700800000, 71.549, 77.49, 69.5, 76.879, 357513.672],
 [1524787200000, 76.879, 77.41, 71.997, 72.318, 306967.74],
 [1524873600000, 72.3, 78.277, 71.92, 76.613, 267303.311],
 [1524960000000, 76.451, 92.493, 75.5, 90.6, 770630.933],
 [1525046400000, 90.552, 94.249, 82.05, 84.0, 580543.028],
 [1525132800000, 83.895, 85.257, 77.812, 84.104, 419931.12],
 [1525219200000, 84.104, 85.434, 82.168, 84.801, 198956.343],
 [1525305600000, 84.889, 90.0, 83.111, 87.707, 381022.138],
 [1525392000000, 87.661, 87.661, 82.137, 84.205, 250032.202],
 [1525478400000, 84.181, 86.5, 83.876, 84.5, 160495.309],
 [1525564800000, 84.591, 88.45, 79.888, 83.766, 314776.56],
 [1525651200000, 83.68, 83.854, 76.1, 79.129, 309166.091],
 [1525737600000, 79.186, 81.75, 75.386, 76.853, 191764.245],
 [1525824000000, 76.826, 77.272, 72.333, 76.158, 166126.746],
 [1525910400000, 76.157, 76.831, 69.54, 69.638, 184251.023],
 [1525996800000, 69.65, 70.41, 60.69, 63.429, 442346.35],
 [1526083200000, 63.41, 67.68, 58.32, 64.559, 366911.835],
 [1526169600000, 64.6, 69.4, 62.51, 67.34, 240380.712],
 [1526256000000, 67.371, 69.09, 62.58, 66.043, 293071.039],
 [1526342400000, 66.043, 69.0, 61.886, 62.85, 183748.244],
 [1526428800000, 62.84, 63.29, 59.11, 61.723, 199291.627],
 [1526515200000, 61.74, 63.9, 56.614, 57.5, 211913.957],
 [1526601600000, 57.47, 60.59, 56.463, 59.69, 216582.393],
 [1526688000000, 59.69, 60.751, 57.872, 59.09, 130400.559],
 [1526774400000, 58.98, 64.248, 58.4, 63.703, 178289.319],
 [1526860800000, 63.703, 66.45, 60.0, 62.133, 261151.668],
 [1526947200000, 62.133, 62.4, 56.555, 56.854, 189272.679],
 [1527033600000, 56.877, 57.758, 51.1, 51.65, 313690.763],
 [1527120000000, 51.711, 55.28, 49.8, 55.15, 231980.712],
 [1527206400000, 55.2, 56.392, 51.7, 52.726, 194508.292],
 [1527292800000, 52.795, 54.5, 51.5, 52.14, 119885.695],
 [1527379200000, 52.15, 52.992, 50.91, 52.93, 86495.349],
 [1527465600000, 52.926, 52.93, 47.5, 47.65, 161625.987],
 [1527552000000, 47.69, 53.88, 47.18, 52.094, 232246.299],
 [1527638400000, 52.21, 53.53, 50.111, 51.462, 171433.091],
 [1527724800000, 51.451, 54.5, 50.726, 53.012, 166583.439],
 [1527811200000, 53.0, 56.312, 52.8, 55.5, 177564.33],
 [1527897600000, 55.5, 57.489, 54.6, 56.792, 181750.978],
 [1527984000000, 56.733, 58.3, 55.419, 56.389, 161466.465],
 [1528070400000, 56.334, 57.25, 52.1, 53.399, 189772.518],
 [1528156800000, 53.399, 54.97, 51.658, 54.511, 154175.847],
 [1528243200000, 54.539, 54.8, 52.369, 53.709, 106177.621],
 [1528329600000, 53.75, 54.99, 52.786, 53.517, 74195.786],
 [1528416000000, 53.463, 53.826, 51.68, 52.195, 73674.517],
 [1528502400000, 52.193, 53.32, 50.54, 50.799, 88932.312],
 [1528588800000, 50.8, 50.8, 44.016, 45.324, 257642.224],
 [1528675200000, 45.278, 45.92, 42.381, 45.593, 170488.645],
 [1528761600000, 45.53, 46.649, 40.25, 41.17, 213433.647],
 [1528848000000, 41.07, 41.681, 35.72, 37.885, 341126.421],
 [1528934400000, 37.883, 41.88, 37.501, 40.656, 394357.8],
 [1529020800000, 40.656, 40.8, 37.688, 37.82, 180421.094],
 [1529107200000, 37.84, 38.572, 36.2, 37.96, 149481.577],
 [1529193600000, 37.997, 39.72, 37.4, 38.56, 130228.407],
 [1529280000000, 38.56, 40.86, 36.828, 39.51, 182824.156],
 [1529366400000, 39.51, 41.45, 38.9, 39.85, 151778.467],
 [1529452800000, 39.836, 40.017, 37.74, 38.866, 145678.491],
 [1529539200000, 38.875, 39.59, 37.241, 37.623, 141424.025],
 [1529625600000, 37.61, 37.734, 32.05, 32.91, 321861.187],
 [1529712000000, 32.91, 34.828, 32.66, 33.847, 176256.36],
 [1529798400000, 33.847, 34.1, 28.634, 31.08, 415801.163],
 [1529884800000, 31.06, 32.79, 30.56, 31.56, 229634.806],
 [1529971200000, 31.536, 31.942, 30.0, 30.001, 135359.557],
 [1530057600000, 30.002, 30.67, 29.382, 30.32, 134328.62],
 [1530144000000, 30.31, 30.64, 27.945, 28.181, 219972.291],
 [1530230400000, 28.197, 30.3, 27.052, 29.534, 294823.651],
 [1530316800000, 29.564, 34.0, 29.554, 30.813, 357338.837],
 [1530403200000, 30.805, 31.69, 29.8, 31.273, 311106.03],
 [1530489600000, 31.279, 37.33, 31.015, 36.159, 642462.865],
 [1530576000000, 36.086, 38.569, 35.32, 35.92, 816826.851],
 [1530662400000, 35.883, 42.618, 35.755, 40.56, 724863.006],
 [1530748800000, 40.56, 43.239, 38.9, 40.217, 761579.759],
 [1530835200000, 40.217, 40.409, 36.864, 37.518, 603877.609],
 [1530921600000, 37.52, 38.75, 36.205, 38.72, 295282.667],
 [1531008000000, 38.721, 41.2, 38.63, 39.045, 681670.264],
 [1531094400000, 39.073, 39.225, 36.19, 36.435, 605267.79],
 [1531180800000, 36.422, 36.899, 32.865, 33.239, 878834.616],
 [1531267200000, 33.266, 34.677, 31.781, 33.814, 645821.445],
 [1531353600000, 33.844, 33.864, 30.476, 32.123, 624803.491],
 [1531440000000, 32.154, 34.2, 31.838, 33.123, 635552.401],
 [1531526400000, 33.117, 33.5, 31.484, 32.415, 384331.357],
 [1531612800000, 32.416, 34.0, 31.99, 33.564, 504854.468],
 [1531699200000, 33.558, 37.318, 32.917, 36.85, 672099.364],
 [1531785600000, 36.761, 40.354, 35.5, 39.221, 935928.251],
 [1531872000000, 39.221, 40.65, 36.499, 37.639, 873965.773],
 [1531958400000, 37.639, 38.111, 35.591, 35.984, 555129.331],
 [1532044800000, 35.984, 36.049, 32.83, 33.138, 582498.851],
 [1532131200000, 33.138, 35.25, 31.97, 34.148, 425432.819],
 [1532217600000, 34.15, 34.899, 32.552, 33.129, 373578.896],
 [1532304000000, 33.109, 34.583, 32.11, 32.11, 431556.952],
 [1532390400000, 32.11, 35.79, 31.26, 33.734, 655323.995],
 [1532476800000, 33.734, 35.55, 33.37, 34.144, 513281.052],
 [1532563200000, 34.11, 35.5, 32.619, 33.038, 501769.324],
 [1532649600000, 33.045, 33.92, 32.156, 33.447, 413764.587],
 [1532736000000, 33.447, 34.075, 32.457, 33.916, 375326.452],
 [1532822400000, 33.913, 34.508, 33.201, 33.395, 326573.773],
 [1532908800000, 33.411, 33.54, 31.423, 31.913, 369204.956],
 [1532995200000, 31.91, 32.14, 29.068, 29.729, 420755.644],
 [1533081600000, 29.73, 30.289, 28.5, 29.664, 420314.381],
 [1533168000000, 29.65, 30.0, 27.65, 28.17, 413945.379],
 [1533254400000, 28.171, 28.48, 26.42, 27.899, 425146.317],
 [1533340800000, 27.879, 28.923, 26.168, 26.729, 423702.218],
 [1533427200000, 26.685, 27.798, 26.147, 27.576, 383712.637],
 [1533513600000, 27.573, 28.337, 25.725, 26.064, 429455.12],
 [1533600000000, 26.095, 27.681, 24.721, 25.098, 493411.847],
 [1533686400000, 25.098, 25.098, 21.013, 21.74, 659118.822],
 [1533772800000, 21.759, 23.0, 20.8, 22.296, 530105.087],
 [1533859200000, 22.297, 22.7, 19.33, 19.759, 559295.654],
 [1533945600000, 19.76, 19.84, 17.341, 18.342, 702108.089],
 [1534032000000, 18.412, 19.251, 18.0, 18.497, 447923.771],
 [1534118400000, 18.457, 18.962, 15.575, 15.672, 609297.373],
 [1534204800000, 15.66, 16.26, 13.8, 16.006, 961386.351],
 [1534291200000, 16.006, 17.691, 15.447, 15.576, 1134877.087],
 [1534377600000, 15.6, 17.25, 15.38, 15.996, 884510.839],
 [1534464000000, 16.002, 20.765, 15.817, 20.67, 1370875.437],
 [1534550400000, 20.67, 21.09, 17.1, 18.731, 1150197.265],
 [1534636800000, 18.697, 20.1, 17.639, 19.505, 918144.963],
 [1534723200000, 19.494, 19.788, 16.83, 17.087, 743607.756],
 [1534809600000, 17.087, 18.241, 16.918, 17.838, 613722.395],
 [1534896000000, 17.837, 19.399, 15.9, 16.375, 871933.6],
 [1534982400000, 16.434, 17.821, 16.366, 17.77, 633368.081],
 [1535068800000, 17.784, 17.926, 16.98, 17.718, 604466.785],
 [1535155200000, 17.719, 18.5, 17.26, 17.595, 654420.865],
 [1535241600000, 17.591, 17.714, 16.741, 17.513, 560146.247],
 [1535328000000, 17.512, 20.816, 17.252, 20.74, 1032669.255],
 [1535414400000, 20.681, 21.74, 19.7, 21.267, 1057017.034],
 [1535500800000, 21.267, 21.331, 19.366, 19.746, 952761.604],
 [1535587200000, 19.721, 20.125, 18.403, 19.56, 759291.051],
 [1535673600000, 19.569, 20.38, 18.92, 20.03, 682248.961],
 [1535760000000, 20.082, 23.27, 20.031, 22.567, 980634.267],
 [1535846400000, 22.551, 23.368, 21.441, 22.116, 1017739.488],
 [1535932800000, 22.115, 23.7, 21.1, 23.005, 903280.584],
 [1536019200000, 23.002, 25.321, 22.4, 24.191, 1227624.195],
 [1536105600000, 24.19, 24.872, 19.117, 19.298, 1782342.348],
 [1536192000000, 19.286, 20.619, 18.001, 20.456, 1707493.35],
 [1536278400000, 20.45, 20.89, 18.7, 19.518, 1185634.522],
 [1536364800000, 19.479, 20.1, 17.597, 17.901, 816063.001],
 [1536451200000, 17.901, 19.39, 17.5, 18.42, 891163.046],
 [1536537600000, 18.406, 19.0, 18.123, 18.494, 666471.519],
 [1536624000000, 18.497, 18.817, 16.901, 17.73, 860817.418],
 [1536710400000, 17.727, 17.799, 16.136, 17.655, 911939.816],
 [1536796800000, 17.646, 18.75, 17.589, 18.243, 1103501.898],
 [1536883200000, 18.229, 18.75, 17.615, 17.735, 859060.432],
 [1536969600000, 17.735, 18.476, 17.735, 17.967, 622069.611],
 [1537056000000, 17.975, 18.127, 17.18, 17.96, 541164.639],
 [1537142400000, 17.963, 18.3, 16.2, 16.491, 1000522.02],
 [1537228800000, 16.498, 17.4, 16.29, 16.863, 628833.602],
 [1537315200000, 16.852, 17.4, 16.25, 17.093, 689844.062],
 [1537401600000, 17.113, 18.574, 16.964, 18.186, 835783.685],
 [1537488000000, 18.186, 20.379, 17.757, 19.846, 1502090.828],
 [1537574400000, 19.844, 20.23, 18.327, 18.84, 691621.16],
 [1537660800000, 18.838, 20.8, 18.643, 19.562, 876987.861],
 [1537747200000, 19.58, 19.72, 18.132, 18.448, 715649.354],
 [1537833600000, 18.446, 18.446, 17.0, 18.209, 649111.046],
 [1537920000000, 18.21, 18.663, 17.383, 17.814, 632178.909],
 [1538006400000, 17.809, 19.33, 17.46, 19.006, 749207.0],
 [1538092800000, 19.024, 20.66, 18.579, 19.272, 1265175.671],
 [1538179200000, 19.243, 19.321, 18.4, 19.16, 584093.955],
 [1538265600000, 19.181, 19.288, 18.5, 18.936, 566345.17],
 [1538352000000, 18.947, 19.158, 18.23, 18.713, 552283.509],
 [1538438400000, 18.695, 18.848, 18.012, 18.451, 547063.362],
 [1538524800000, 18.453, 18.518, 17.688, 18.026, 544804.598],
 [1538611200000, 18.026, 18.4, 17.9, 17.996, 532363.951],
 [1538697600000, 17.996, 18.335, 17.8, 18.207, 467505.862],
 [1538784000000, 18.224, 18.62, 17.83, 17.961, 476808.479],
 [1538870400000, 17.943, 18.29, 17.9, 18.207, 457368.991],
 [1538956800000, 18.219, 18.824, 18.116, 18.558, 634233.569],
 [1539043200000, 18.558, 18.624, 18.05, 18.329, 564358.002],
 [1539129600000, 18.329, 18.39, 17.881, 18.267, 516770.513],
 [1539216000000, 18.26, 18.294, 15.401, 15.57, 945106.086],
 [1539302400000, 15.549, 16.294, 15.25, 15.747, 463041.259],
 [1539388800000, 15.707, 16.094, 15.701, 15.958, 413719.079],
 [1539475200000, 15.97, 16.469, 15.649, 15.814, 528065.344],
 [1539561600000, 15.784, 18.7, 15.514, 16.656, 1153037.853],
 [1539648000000, 16.655, 16.961, 16.4, 16.867, 437450.075],
 [1539734400000, 16.842, 17.333, 16.72, 17.179, 551933.463],
 [1539820800000, 17.168, 18.162, 16.711, 16.922, 748598.243],
 [1539907200000, 16.92, 17.035, 16.6, 16.737, 352920.885],
 [1539993600000, 16.737, 17.113, 16.521, 16.903, 434063.999],
 [1540080000000, 16.903, 17.2, 16.72, 16.795, 453858.762],
 [1540166400000, 16.775, 17.292, 16.617, 17.05, 417179.855],
 [1540252800000, 17.039, 17.071, 16.68, 16.827, 198544.389],
 [1540339200000, 16.827, 17.095, 16.73, 16.934, 261913.004],
 [1540425600000, 16.934, 16.965, 16.65, 16.709, 175532.541],
 [1540512000000, 16.71, 16.784, 15.87, 16.386, 266332.782],
 [1540598400000, 16.403, 16.536, 16.075, 16.134, 162077.407],
 [1540684800000, 16.134, 16.3, 16.089, 16.217, 141535.863],
 [1540771200000, 16.22, 16.299, 15.0, 15.465, 288370.818],
 [1540857600000, 15.464, 15.561, 15.16, 15.248, 174422.188],
 [1540944000000, 15.248, 15.529, 14.599, 15.468, 254426.662],
 [1541030400000, 15.468, 15.9, 15.272, 15.84, 175893.014],
 [1541116800000, 15.839, 16.353, 15.818, 16.296, 247793.532],
 [1541203200000, 16.296, 16.312, 15.806, 15.984, 184211.712],
 [1541289600000, 16.008, 17.197, 15.82, 16.897, 363855.542],
 [1541376000000, 16.91, 16.92, 16.28, 16.415, 227442.096],
 [1541462400000, 16.423, 17.192, 16.415, 17.118, 303220.142],
 [1541548800000, 17.1, 17.583, 16.606, 16.832, 331675.759],
 [1541635200000, 16.831, 16.942, 16.329, 16.409, 211878.974],
 [1541721600000, 16.398, 16.597, 15.9, 16.008, 137192.077],
 [1541808000000, 16.019, 16.398, 15.96, 15.991, 98493.351],
 [1541894400000, 15.992, 16.23, 15.51, 16.18, 143606.31],
 [1541980800000, 16.181, 16.35, 15.7, 15.923, 133578.913],
 [1542067200000, 15.939, 15.945, 15.505, 15.571, 170848.359],
 [1542153600000, 15.571, 15.62, 12.815, 13.946, 568213.503],
 [1542240000000, 13.919, 14.02, 12.202, 13.269, 583575.913],
 [1542326400000, 13.267, 13.337, 12.6, 12.873, 318948.265],
 [1542412800000, 12.862, 12.884, 12.48, 12.59, 160425.9],
 [1542499200000, 12.591, 12.85, 12.51, 12.686, 171576.741],
 [1542585600000, 12.686, 12.686, 10.1, 10.271, 819771.934],
 [1542672000000, 10.255, 10.6, 8.21, 9.127, 1616246.744],
 [1542758400000, 9.144, 9.591, 8.671, 9.357, 1086921.525],
 [1542844800000, 9.357, 9.505, 8.355, 8.429, 719424.328],
 [1542931200000, 8.429, 8.889, 8.023, 8.742, 903145.217],
 [1543017600000, 8.734, 9.127, 7.362, 7.586, 699961.19],
 [1543104000000, 7.585, 8.188, 6.86, 7.841, 1203935.622],
 [1543190400000, 7.841, 8.057, 7.0, 7.28, 1058279.821],
 [1543276800000, 7.267, 7.45, 6.81, 7.358, 620891.247],

In [ ]:
time_close_dict[]

{1514764800000: 13380.0,
 1514851200000: 14675.11,
 1514937600000: 14919.51,
 1515024000000: 15059.54,
 1515110400000: 16960.39,
 1515196800000: 17069.79,
 1515283200000: 16150.03,
 1515369600000: 14902.54,
 1515456000000: 14400.0,
 1515542400000: 14907.09,
 1515628800000: 13238.78,
 1515715200000: 13740.01,
 1515801600000: 14210.0,
 1515888000000: 13474.99,
 1515974400000: 13539.93,
 1516060800000: 10900.0,
 1516147200000: 10988.79,
 1516233600000: 10961.97,
 1516320000000: 11474.98,
 1516406400000: 12799.94,
 1516492800000: 11530.0,
 1516579200000: 10760.05,
 1516665600000: 10799.18,
 1516752000000: 11349.99,
 1516838400000: 11175.27,
 1516924800000: 11089.0,
 1517011200000: 11491.0,
 1517097600000: 11879.95,
 1517184000000: 11251.0,
 1517270400000: 10237.51,
 1517356800000: 10285.1,
 1517443200000: 9224.52,
 1517529600000: 8873.03,
 1517616000000: 9199.96,
 1517702400000: 8184.81,
 1517788800000: 6939.99,
 1517875200000: 7652.14,
 1517961600000: 7599.0,
 1518048000000: 7784.02,
 1518134400000: 8683.92,
 1518220800000: 8533.98,
 1518307200000: 8063.88,
 1518393600000: 8903.0,
 1518480000000: 8539.9,
 1518566400000: 9449.99,
 1518652800000: 10000.09,
 1518739200000: 10159.98,
 1518825600000: 11039.55,
 1518912000000: 10383.43,
 1518998400000: 11153.0,
 1519084800000: 11200.99,
 1519171200000: 10437.6,
 1519257600000: 9811.04,
 1519344000000: 10131.04,
 1519430400000: 9694.51,
 1519516800000: 9590.0,
 1519603200000: 10324.0,
 1519689600000: 10569.04,
 1519776000000: 10326.76,
 1519862400000: 10920.0,
 1519948800000: 11039.0,
 1520035200000: 11464.48,
 1520121600000: 11515.0,
 1520208000000: 11454.0,
 1520294400000: 10716.48,
 1520380800000: 9910.0,
 1520467200000: 9271.64,
 1520553600000: 9227.0,
 1520640000000: 8770.22,
 1520726400000: 9533.57,
 1520812800000: 9131.34,
 1520899200000: 9150.0,
 1520985600000: 8170.0,
 1521072000000: 8240.98,
 1521158400000: 8260.0,
 1521244800000: 7824.8,
 1521331200000: 8189.99,
 1521417600000: 8600.0,
 1521504000000: 8909.98,
 1521590400000: 8885.0,
 1521676800000: 8722.9,
 1521763200000: 8898.03,
 1521849600000: 8546.86,
 1521936000000: 8470.15,
 1522022400000: 8134.23,
 1522108800000: 7795.51,
 1522195200000: 7949.3,
 1522281600000: 7090.14,
 1522368000000: 6840.23,
 1522454400000: 6923.91,
 1522540800000: 6813.01,
 1522627200000: 7056.0,
 1522713600000: 7405.21,
 1522800000000: 6796.1,
 1522886400000: 6770.76,
 1522972800000: 6601.39,
 1523059200000: 6895.8,
 1523145600000: 7018.0,
 1523232000000: 6782.72,
 1523318400000: 6843.9,
 1523404800000: 6953.79,
 1523491200000: 7923.0,
 1523577600000: 7877.41,
 1523664000000: 7999.01,
 1523750400000: 8355.0,
 1523836800000: 8064.92,
 1523923200000: 7885.02,
 1524009600000: 8173.0,
 1524096000000: 8278.0,
 1524182400000: 8856.98,
 1524268800000: 8915.31,
 1524355200000: 8787.02,
 1524441600000: 8934.01,
 1524528000000: 9619.99,
 1524614400000: 8869.99,
 1524700800000: 9266.0,
 1524787200000: 8915.35,
 1524873600000: 9348.0,
 1524960000000: 9419.0,
 1525046400000: 9246.01,
 1525132800000: 9071.48,
 1525219200000: 9247.84,
 1525305600000: 9750.0,
 1525392000000: 9713.99,
 1525478400000: 9864.0,
 1525564800000: 9659.01,
 1525651200000: 9365.0,
 1525737600000: 9187.56,
 1525824000000: 9310.0,
 1525910400000: 9002.2,
 1525996800000: 8400.0,
 1526083200000: 8465.94,
 1526169600000: 8679.71,
 1526256000000: 8663.34,
 1526342400000: 8462.0,
 1526428800000: 8330.0,
 1526515200000: 8041.46,
 1526601600000: 8239.81,
 1526688000000: 8233.49,
 1526774400000: 8526.98,
 1526860800000: 8381.24,
 1526947200000: 7977.11,
 1527033600000: 7501.95,
 1527120000000: 7575.01,
 1527206400000: 7457.0,
 1527292800000: 7333.96,
 1527379200000: 7338.99,
 1527465600000: 7099.0,
 1527552000000: 7461.29,
 1527638400000: 7375.96,
 1527724800000: 7485.01,
 1527811200000: 7521.01,
 1527897600000: 7640.03,
 1527984000000: 7714.26,
 1528070400000: 7487.0,
 1528156800000: 7625.0,
 1528243200000: 7658.84,
 1528329600000: 7691.08,
 1528416000000: 7603.44,
 1528502400000: 7491.73,
 1528588800000: 6764.99,
 1528675200000: 6872.0,
 1528761600000: 6530.0,
 1528848000000: 6292.78,
 1528934400000: 6635.98,
 1529020800000: 6388.9,
 1529107200000: 6483.98,
 1529193600000: 6449.61,
 1529280000000: 6712.46,
 1529366400000: 6741.21,
 1529452800000: 6761.51,
 1529539200000: 6718.84,
 1529625600000: 6045.0,
 1529712000000: 6149.98,
 1529798400000: 6136.97,
 1529884800000: 6252.0,
 1529971200000: 6070.78,
 1530057600000: 6133.73,
 1530144000000: 5853.98,
 1530230400000: 6197.92,
 1530316800000: 6390.07,
 1530403200000: 6356.81,
 1530489600000: 6615.29,
 1530576000000: 6513.86,
 1530662400000: 6586.98,
 1530748800000: 6529.2,
 1530835200000: 6609.78,
 1530921600000: 6756.98,
 1531008000000: 6712.1,
 1531094400000: 6662.12,
 1531180800000: 6296.91,
 1531267200000: 6378.07,
 1531353600000: 6250.57,
 1531440000000: 6214.57,
 1531526400000: 6251.99,
 1531612800000: 6353.01,
 1531699200000: 6723.35,
 1531785600000: 7317.44,
 1531872000000: 7381.9,
 1531958400000: 7466.21,
 1532044800000: 7337.53,
 1532131200000: 7398.78,
 1532217600000: 7394.79,
 1532304000000: 7721.01,
 1532390400000: 8397.24,
 1532476800000: 8175.64,
 1532563200000: 7920.0,
 1532649600000: 8188.57,
 1532736000000: 8225.04,
 1532822400000: 8211.0,
 1532908800000: 8173.92,
 1532995200000: 7730.93,
 1533081600000: 7604.58,
 1533168000000: 7525.71,
 1533254400000: 7418.78,
 1533340800000: 7009.84,
 1533427200000: 7024.19,
 1533513600000: 6934.82,
 1533600000000: 6720.06,
 1533686400000: 6285.0,
 1533772800000: 6529.79,
 1533859200000: 6144.01,
 1533945600000: 6232.35,
 1534032000000: 6308.33,
 1534118400000: 6246.35,
 1534204800000: 6188.08,
 1534291200000: 6267.16,
 1534377600000: 6311.75,
 1534464000000: 6584.49,
 1534550400000: 6387.96,
 1534636800000: 6477.53,
 1534723200000: 6254.84,
 1534809600000: 6480.0,
 1534896000000: 6360.89,
 1534982400000: 6525.01,
 1535068800000: 6681.64,
 1535155200000: 6733.64,
 1535241600000: 6700.0,
 1535328000000: 6908.64,
 1535414400000: 7076.11,
 1535500800000: 7031.22,
 1535587200000: 6984.84,
 1535673600000: 7011.21,
 1535760000000: 7200.01,
 1535846400000: 7302.01,
 1535932800000: 7263.02,
 1536019200000: 7359.06,
 1536105600000: 6700.0,
 1536192000000: 6516.01,
 1536278400000: 6395.54,
 1536364800000: 6185.05,
 1536451200000: 6250.81,
 1536537600000: 6312.0,
 1536624000000: 6294.91,
 1536710400000: 6338.62,
 1536796800000: 6487.38,
 1536883200000: 6476.63,
 1536969600000: 6514.96,
 1537056000000: 6505.0,
 1537142400000: 6248.69,
 1537228800000: 6336.45,
 1537315200000: 6391.89,
 1537401600000: 6492.0,
 1537488000000: 6759.02,
 1537574400000: 6723.05,
 1537660800000: 6708.0,
 1537747200000: 6581.39,
 1537833600000: 6447.54,
 1537920000000: 6465.12,
 1538006400000: 6689.13,
 1538092800000: 6634.58,
 1538179200000: 6596.38,
 1538265600000: 6626.57,
 1538352000000: 6611.61,
 1538438400000: 6525.79,
 1538524800000: 6510.0,
 1538611200000: 6593.79,
 1538697600000: 6635.65,
 1538784000000: 6594.27,
 1538870400000: 6615.26,
 1538956800000: 6673.01,
 1539043200000: 6656.61,
 1539129600000: 6631.0,
 1539216000000: 6252.68,
 1539302400000: 6298.01,
 1539388800000: 6332.93,
 1539475200000: 6339.34,
 1539561600000: 6752.5,
 1539648000000: 6759.27,
 1539734400000: 6740.89,
 1539820800000: 6618.96,
 1539907200000: 6528.88,
 1539993600000: 6588.4,
 1540080000000: 6590.11,
 1540166400000: 6581.2,
 1540252800000: 6553.51,
 1540339200000: 6565.5,
 1540425600000: 6528.09,
 1540512000000: 6538.63,
 1540598400000: 6505.6,
 1540684800000: 6489.93,
 1540771200000: 6344.5,
 1540857600000: 6330.87,
 1540944000000: 6371.93,
 1541030400000: 6410.0,
 1541116800000: 6433.98,
 1541203200000: 6387.09,
 1541289600000: 6485.85,
 1541376000000: 6468.99,
 1541462400000: 6519.11,
 1541548800000: 6578.46,
 1541635200000: 6479.84,
 1541721600000: 6419.99,
 1541808000000: 6433.05,
 1541894400000: 6449.81,
 1541980800000: 6453.07,
 1542067200000: 6457.66,
 1542153600000: 5922.41,
 1542240000000: 5753.4,
 1542326400000: 5655.94,
 1542412800000: 5628.29,
 1542499200000: 5662.0,
 1542585600000: 4910.03,
 1542672000000: 4558.86,
 1542758400000: 4661.07,
 1542844800000: 4370.0,
 1542931200000: 4420.61,
 1543017600000: 3932.44,
 1543104000000: 4085.78,
 1543190400000: 3862.2,
 1543276800000: 3875.21,
 1543363200000: 4264.85,
 1543449600000: 4295.84,
 1543536000000: 4041.32,
 1543622400000: 4190.02,
 1543708800000: 4161.01,
 1543795200000: 3884.01,
 1543881600000: 3951.64,
 1543968000000: 3769.84,
 1544054400000: 3508.75,
 1544140800000: 3403.55,
 1544227200000: 3410.93,
 1544313600000: 3545.37,
 1544400000000: 3432.88,
 1544486400000: 3380.39,
 1544572800000: 3445.0,
 1544659200000: 3302.06,
 1544745600000: 3224.17,
 1544832000000: 3211.72,
 1544918400000: 3228.67,
 1545004800000: 3509.08,
 1545091200000: 3652.98,
 1545177600000: 3662.22,
 1545264000000: 4049.62,
 1545350400000: 3838.66,
 1545436800000: 3948.91,
 1545523200000: 3929.71,
 1545609600000: 4008.01,
 1545696000000: 3745.79,
 1545782400000: 3777.74,
 1545868800000: 3567.91,
 1545955200000: 3839.26,
 1546041600000: 3695.32,
 1546128000000: 3801.91,
 1546214400000: 3702.9,
 1546300800000: 3797.14,
 1546387200000: 3858.56,
 1546473600000: 3766.78,
 1546560000000: 3792.01,
 1546646400000: 3770.96,
 1546732800000: 3987.6,
 1546819200000: 3975.45,
 1546905600000: 3955.13,
 1546992000000: 3966.65,
 1547078400000: 3585.88,
 1547164800000: 3601.31,
 1547251200000: 3583.13,
 1547337600000: 3476.81,
 1547424000000: 3626.09,
 1547510400000: 3553.06,
 1547596800000: 3591.84,
 1547683200000: 3616.21,
 1547769600000: 3594.87,
 1547856000000: 3665.3,
 1547942400000: 3539.28,
 1548028800000: 3526.9,
 1548115200000: 3570.93,
 1548201600000: 3552.82,
 1548288000000: 3569.62,
 1548374400000: 3565.29,
 1548460800000: 3565.25,
 1548547200000: 3550.84,
 1548633600000: 3434.15,
 1548720000000: 3411.04,
 1548806400000: 3458.18,
 1548892800000: 3434.1,
 1548979200000: 3462.07,
 1549065600000: 3504.77,
 1549152000000: 3458.11,
 1549238400000: 3463.22,
 1549324800000: 3471.59,
 1549411200000: 3405.37,
 1549497600000: 3398.4,
 1549584000000: 3659.04,
 1549670400000: 3665.18,
 1549756800000: 3680.06,
 1549843200000: 3631.05,
 1549929600000: 3631.46,
 1550016000000: 3609.4,
 1550102400000: 3590.56,
 1550188800000: 3602.47,
 1550275200000: 3618.41,
 1550361600000: 3667.58,
 1550448000000: 3898.6,
 1550534400000: 3907.79,
 1550620800000: 3969.74,
 1550707200000: 3937.31,
 1550793600000: 3962.0,
 1550880000000: 4117.76,
 1550966400000: 3743.56,
 1551052800000: 3827.92,
 1551139200000: 3809.23,
 1551225600000: 3818.07,
 1551312000000: 3813.69,
 1551398400000: 3823.0,
 1551484800000: 3819.93,
 1551571200000: 3807.75,
 1551657600000: 3715.3,
 1551744000000: 3857.73,
 1551830400000: 3861.84,
 1551916800000: 3873.64,
 1552003200000: 3864.89,
 1552089600000: 3943.04,
 1552176000000: 3916.82,
 1552262400000: 3871.61,
 1552348800000: 3882.73,
 1552435200000: 3866.0,
 1552521600000: 3877.12,
 1552608000000: 3923.76,
 1552694400000: 4005.98,
 1552780800000: 3981.14,
 1552867200000: 3987.81,
 1552953600000: 4015.53,
 1553040000000: 4043.04,
 1553126400000: 3980.64,
 1553212800000: 3986.93,
 1553299200000: 4006.01,
 1553385600000: 3992.18,
 1553472000000: 3936.12,
 1553558400000: 3948.55,
 1553644800000: 4038.05,
 1553731200000: 4027.81,
 1553817600000: 4103.25,
 1553904000000: 4106.97,
 1553990400000: 4103.95,
 1554076800000: 4144.56,
 1554163200000: 4857.29,
 1554249600000: 4932.6,
 1554336000000: 4898.66,
 1554422400000: 5004.95,
 1554508800000: 5043.89,
 1554595200000: 5170.27,
 1554681600000: 5236.9,
 1554768000000: 5150.0,
 1554854400000: 5308.25,
 1554940800000: 5017.37,
 1555027200000: 5048.01,
 1555113600000: 5045.22,
 1555200000000: 5131.3,
 1555286400000: 5024.95,
 1555372800000: 5173.72,
 1555459200000: 5202.82,
 1555545600000: 5258.44,
 1555632000000: 5258.68,
 1555718400000: 5291.73,
 1555804800000: 5256.14,
 1555891200000: 5357.14,
 1555977600000: 5493.31,
 1556064000000: 5415.0,
 1556150400000: 5219.9,
 1556236800000: 5314.1,
 1556323200000: 5295.69,
 1556409600000: 5307.52,
 1556496000000: 5238.14,
 1556582400000: 5320.81,
 1556668800000: 5383.2,
 1556755200000: 5492.87,
 1556841600000: 5772.69,
 1556928000000: 5829.45,
 1557014400000: 5775.62,
 1557100800000: 5747.79,
 1557187200000: 5846.34,
 1557273600000: 5987.29,
 1557360000000: 6209.18,
 1557446400000: 6373.33,
 1557532800000: 7076.22,
 1557619200000: 6967.31,
 1557705600000: 7790.71,
 1557792000000: 7947.56,
 1557878400000: 8169.87,
 1557964800000: 7866.59,
 1558051200000: 7355.26,
 1558137600000: 7257.45,
 1558224000000: 8148.48,
 1558310400000: 7938.15,
 1558396800000: 7904.87,
 1558483200000: 7628.43,
 1558569600000: 7851.51,
 1558656000000: 7964.87,
 1558742400000: 8025.41,
 1558828800000: 8614.43,
 1558915200000: 8756.32,
 1559001600000: 8715.64,
 1559088000000: 8645.68,
 1559174400000: 8269.54,
 1559260800000: 8555.0,
 1559347200000: 8544.07,
 1559433600000: 8725.98,
 1559520000000: 8115.82,
 1559606400000: 7687.03,
 1559692800000: 7776.5,
 1559779200000: 7786.7,
 1559865600000: 7980.53,
 1559952000000: 7893.62,
 1560038400000: 7628.13,
 1560124800000: 7982.75,
 1560211200000: 7884.9,
 1560297600000: 8127.64,
 1560384000000: 8218.54,
 1560470400000: 8650.0,
 1560556800000: 8808.7,
 1560643200000: 8953.33,
 1560729600000: 9313.96,
 1560816000000: 9081.55,
 1560902400000: 9255.49,
 1560988800000: 9517.12,
 1561075200000: 10159.86,
 1561161600000: 10729.5,
 1561248000000: 10906.07,
 1561334400000: 11056.59,
 1561420800000: 11820.86,
 1561507200000: 13093.8,
 1561593600000: 11329.99,
 1561680000000: 12400.63,
 1561766400000: 11903.13,
 1561852800000: 10854.1,
 1561939200000: 10624.93,
 1562025600000: 10842.85,
 1562112000000: 11940.0,
 1562198400000: 11145.67,
 1562284800000: 10970.73,
 1562371200000: 11256.49,
 1562457600000: 11406.24,
 1562544000000: 12238.6,
 1562630400000: 12543.41,
 1562716800000: 12108.37,
 1562803200000: 11342.89,
 1562889600000: 11757.22,
 1562976000000: 11355.76,
 1563062400000: 10174.18,
 1563148800000: 10838.72,
 1563235200000: 9439.59,
 1563321600000: 9667.92,
 1563408000000: 10627.16,
 1563494400000: 10504.29,
 1563580800000: 10740.23,
 1563667200000: 10589.45,
 1563753600000: 10340.31,
 1563840000000: 9864.91,
 1563926400000: 9763.28,
 1564012800000: 9879.87,
 1564099200000: 9824.0,
 1564185600000: 9476.52,
 1564272000000: 9541.54,
 1564358400000: 9507.64,
 1564444800000: 9574.21,
 1564531200000: 10080.53,
 1564617600000: 10374.99,
 1564704000000: 10523.75,
 1564790400000: 10816.86,
 1564876800000: 10929.23,
 1564963200000: 11828.8,
 1565049600000: 11481.69,
 1565136000000: 11975.03,
 1565222400000: 11999.77,
 1565308800000: 11879.99,
 1565395200000: 11309.31,
 1565481600000: 11549.97,
 1565568000000: 11396.08,
 1565654400000: 10892.71,
 1565740800000: 10050.37,
 1565827200000: 10293.93,
 1565913600000: 10331.54,
 1566000000000: 10216.02,
 1566086400000: 10306.78,
 1566172800000: 10915.54,
 1566259200000: 10760.51,
 1566345600000: 10142.57,
 1566432000000: 10099.88,
 1566518400000: 10389.55,
 1566604800000: 10134.35,
 1566691200000: 10142.69,
 1566777600000: 10372.25,
 1566864000000: 10185.05,
 1566950400000: 9721.0,
 1567036800000: 9498.44,
 1567123200000: 9584.54,
 1567209600000: 9587.47,
 1567296000000: 9724.98,
 1567382400000: 10340.0,
 1567468800000: 10615.28,
 1567555200000: 10567.02,
 1567641600000: 10564.49,
 1567728000000: 10298.73,
 1567814400000: 10455.88,
 1567900800000: 10381.18,
 1567987200000: 10303.12,
 1568073600000: 10098.15,
 1568160000000: 10158.33,
 1568246400000: 10415.01,
 1568332800000: 10342.06,
 1568419200000: 10335.02,
 1568505600000: 10302.01,
 1568592000000: 10251.31,
 1568678400000: 10187.82,
 1568764800000: 10156.99,
 1568851200000: 10244.29,
 1568937600000: 10168.59,
 1569024000000: 9986.39,
 1569110400000: 10028.87,
 1569196800000: 9702.25,
 1569283200000: 8493.14,
 1569369600000: 8430.05,
 1569456000000: 8063.73,
 1569542400000: 8177.91,
 1569628800000: 8198.81,
 1569715200000: 8043.82,
 1569801600000: 8289.34,
 1569888000000: 8292.44,
 1569974400000: 8359.94,
 1570060800000: 8223.96,
 1570147200000: 8137.13,
 1570233600000: 8126.19,
 1570320000000: 7854.25,
 1570406400000: 8190.09,
 1570492800000: 8168.39,
 1570579200000: 8560.74,
 1570665600000: 8558.03,
 1570752000000: 8258.5,
 1570838400000: 8300.09,
 1570924800000: 8275.01,
 1571011200000: 8348.2,
 1571097600000: 8159.29,
 1571184000000: 7991.74,
 1571270400000: 8070.58,
 1571356800000: 7947.01,
 1571443200000: 7948.01,
 1571529600000: 8223.35,
 1571616000000: 8197.27,
 1571702400000: 8020.0,
 1571788800000: 7466.62,
 1571875200000: 7412.41,
 1571961600000: 8655.02,
 1572048000000: 9230.0,
 1572134400000: 9529.93,
 1572220800000: 9205.14,
 1572307200000: 9407.62,
 1572393600000: 9154.72,
 1572480000000: 9140.85,
 1572566400000: 9231.61,
 1572652800000: 9289.52,
 1572739200000: 9194.71,
 1572825600000: 9393.35,
 1572912000000: 9308.66,
 1572998400000: 9339.05,
 1573084800000: 9216.2,
 1573171200000: 8773.73,
 1573257600000: 8809.41,
 1573344000000: 9039.47,
 1573430400000: 8733.27,
 1573516800000: 8821.94,
 1573603200000: 8777.12,
 1573689600000: 8646.68,
 1573776000000: 8471.73,
 1573862400000: 8491.02,
 1573948800000: 8502.4,
 1574035200000: 8187.17,
 1574121600000: 8133.64,
 1574208000000: 8098.01,
 1574294400000: 7627.74,
 1574380800000: 7268.23,
 1574467200000: 7311.57,
 1574553600000: 6903.28,
 1574640000000: 7109.57,
 1574726400000: 7156.14,
 1574812800000: 7508.52,
 1574899200000: 7419.49,
 1574985600000: 7739.68,
 1575072000000: 7541.89,
 1575158400000: 7390.89,
 1575244800000: 7294.28,
 1575331200000: 7292.71,
 1575417600000: 7194.32,
 1575504000000: 7389.0,
 1575590400000: 7527.47,
 1575676800000: 7488.21,
 1575763200000: 7510.11,
 1575849600000: 7338.64,
 1575936000000: 7224.13,
 1576022400000: 7210.0,
 1576108800000: 7198.08,
 1576195200000: 7258.48,
 1576281600000: 7064.05,
 1576368000000: 7118.59,
 1576454400000: 6891.72,
 1576540800000: 6623.82,
 1576627200000: 7277.83,
 1576713600000: 7150.3,
 1576800000000: 7187.83,
 1576886400000: 7132.75,
 1576972800000: 7501.44,
 1577059200000: 7317.09,
 1577145600000: 7255.77,
 1577232000000: 7204.63,
 1577318400000: 7202.0,
 1577404800000: 7254.74,
 1577491200000: 7316.14,
 1577577600000: 7388.24,
 1577664000000: 7246.0,
 1577750400000: 7195.23}

In [ ]:
time_close_dict

In [ ]:
close_dict = {}
for symbol in symbols:
    all_data = exchange.fetch_ohlcv(symbol, timeframe, since=start_ts, limit=1000)
    temp_close_dict = {c[0]: c[4] for c in all_data if c[0] <= end_ts}
    close_dict[symbol] = temp_close_dict
    
df = pd.DataFrame(close_dict)
df.index = pd.to_datetime(df.index, unit='ms')
df.index.name = 'date'
df.to_csv('../data/close_price_data.csv', index=True)

In [ ]:
panel_a_start = '2018-01-01'
panel_a_end = '2018-06-30'
panel_b_start = '2018-07-01'
panel_b_end = '2018-12-31'
panel_c_start = '2019-01-01'
panel_c_end = '2019-06-30'
panel_d_start = '2019-07-01'
panel_d_end = '2019-12-31'

df_a = df.loc[panel_a_start : panel_a_end]
df_b = df.loc[panel_b_start : panel_b_end]
df_c = df.loc[panel_c_start : panel_c_end]
df_d = df.loc[panel_d_start : panel_d_end]

In [108]:
df = pd.read_csv('../data/close_price_data.csv', index_col=0, parse_dates=True)
df.tail()

            BTC/USDT  ETH/USDT  LTC/USDT  NEO/USDT
date
2019-12-27   7254.74    126.29     40.95     8.723
2019-12-28   7316.14    128.11     42.83     8.766
2019-12-29   7388.24    134.36     43.08     9.201
2019-12-30   7246.00    131.59     42.38     8.943
2019-12-31   7195.23    129.16     41.30     8.678

In [89]:
df.index

RangeIndex(start=0, stop=730, step=1)

In [99]:
date_ranges = {
        'panel_a': ('2018-01-01', '2018-06-30'),
        'panel_b': ('2018-07-01', '2018-12-31'),
        'panel_c': ('2019-01-01', '2019-06-30'),
        'panel_d': ('2019-07-01', '2019-12-31')
    }

for panel_name, (start_date, end_date) in date_ranges.items():
        panel_df = df.loc[start_date:end_date]
        
        file_path = f"../data/{panel_name}.csv"
        panel_df.to_csv(file_path)
        print(f"Saved {panel_name} with {len(panel_df)} rows.")

Saved panel_a with 181 rows.
Saved panel_b with 184 rows.
Saved panel_c with 181 rows.
Saved panel_d with 184 rows.

In [100]:
DATA_PATH = '../data/'

In [106]:
f'{DATA_PATH}{panel_name}'

'../data/panel_d'

In [110]:
import os
os.path.exists(f'{DATA_PATH}{panel_name}.csv')

True

In [113]:
from itertools import combinations

pairs = list(combinations(symbols , 2))

In [117]:
panels = {}
panel_names = ['panel_a', 'panel_b', 'panel_c', 'panel_d']
    
for name in panel_names:
        file_path = f"{DATA_PATH}{name}.csv"
        panels[name] = pd.read_csv(file_path, index_col=0, parse_dates=True)

In [ ]:
for key, value in panels.items():
     columns = list(value.columns)
     pairs = list(combinations(columns, 2))

     for pair in pairs:

['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'NEO/USDT']
['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'NEO/USDT']
['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'NEO/USDT']
['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'NEO/USDT']

In [143]:
import statsmodels.api as sm

In [150]:
y  = panels['panel_a']['BTC/USDT']
x = panels['panel_a']['ETH/USDT']

x = sm.add_constant(x)

In [151]:
model = sm.OLS(y, x).fit()

In [167]:
print(model.params['ETH/USDT'])

8.22307214912503

In [164]:
series = pd.Series(model.resid)
from statsmodels.tsa.stattools import adfuller

result = adfuller(series)

np.float64(1235.1086693575332)

In [170]:
result[1]

np.float64(0.0015114506705803386)

In [154]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               BTC/USDT   R-squared:                       0.705
Model:                            OLS   Adj. R-squared:                  0.703
Method:                 Least Squares   F-statistic:                     427.5
Date:                Sun, 17 May 2026   Prob (F-statistic):           2.62e-49
Time:                        14:48:06   Log-Likelihood:                -1544.8
No. Observations:                 181   AIC:                             3094.
Df Residuals:                     179   BIC:                             3100.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3206.2276    299.153     10.718      0.000    2615.907    3796.548
ETH/USDT       8.2231      0.398     20.675      0.000       7.438       9.008
==============================================================================
Omnibus:                       87.231   Durbin-Watson:                   0.081
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              395.402
Skew:                           1.836   Prob(JB):                     1.38e-86
Kurtosis:                       9.240   Cond. No.                     2.44e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.44e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [139]:
pairs

[('BTC/USDT', 'ETH/USDT'),
 ('BTC/USDT', 'LTC/USDT'),
 ('BTC/USDT', 'NEO/USDT'),
 ('ETH/USDT', 'LTC/USDT'),
 ('ETH/USDT', 'NEO/USDT'),
 ('LTC/USDT', 'NEO/USDT')]

In [ ]:
for pair in pairs:
    coin1 = pair[0]
    coin2 = pair[1]
    coin1_mean = value[coin1].mean()
    coin2_mean = value[coin2].mean()
    highest = max(coin1 , coin2)
    lowest = min(coin1, coin2)

    print({coin1: })

9168.937771739129
186.89271739130436
9168.937771739129
67.2558152173913
9168.937771739129
10.067467391304346
186.89271739130436
67.2558152173913
186.89271739130436
10.067467391304346
67.2558152173913
10.067467391304346

In [107]:
pd.read_csv(DATA_PATH + 'panel_a.csv' ,index_col=0, parse_dates=True)

            BTC/USDT  ETH/USDT  LTC/USDT  NEO/USDT
date
2018-01-01  13380.00    754.99    222.61    78.299
2018-01-02  14675.11    855.28    247.33    89.696
2018-01-03  14919.51    934.03    238.77   103.505
2018-01-04  15059.54    940.00    233.00    97.669
2018-01-05  16960.39    959.30    240.54    95.134
...              ...       ...       ...       ...
2018-06-26   6070.78    429.34     75.54    30.001
2018-06-27   6133.73    441.64     80.60    30.320
2018-06-28   5853.98    420.22     74.05    28.181
2018-06-29   6197.92    434.77     78.94    29.534
2018-06-30   6390.07    454.09     81.33    30.813

[181 rows x 4 columns]